version: "3.3"
services:
  kapowarr:
    container_name: kapowarr
    image: mrcas/kapowarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC 
    volumes:
      - "kapowarr-db:/app/db"
      - "/path/to/download_folder:/app/temp_downloads"
      - "/path/to/comics:/comics"
    ports:
      - 5656:5656

volumes:
  kapowarr-db:
